### ISSUE TITLE
how do you even open it

### ISSUE THREAD

**Issue by Choco1412** [zqad/zmask#1]
???

**Comment by Xeddius** [comment]
If you don't know how to run a .jar file, what business do you have using it?
Anyway, criticism aside, you can run this on linux, windows or mac with the following commands.
Linux: Java -jar zmask-v0.1.jar
Windows: Java.exe -jar zmask-v0.1.jar
Mac: Java -jar zmask-v0.1.jar

**Comment by zqad** [comment]
Hi there,

Sorry about the delay in answering this, but @Xeddius provided a correct way. I have added this into the README.md for future reference.

/Jonas
